### ISSUE TITLE
Cannot access geonetwork webapp on branch 23.0 when logged in

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/docker#237] opened 2023-10-18 17:48 UTC
I'm running the composition for branch 23.0, brand new from the repo. I can access GN fine when not logged in (as anonymousUser). But once I've logged in as testadmin, I can't access geonetwork anymore (both public and admin interface). In the logs, the proxy is giving me an error related to setOAuth2ProviderId. Could this be a regression due to the Oauth2 support ?
Here the log trace:

```
docker-proxy-1                            | 2023-10-18 17:42:58.065:WARN:oejs.HttpChannel:qtp92150540-122: /geonetwork/
docker-proxy-1                            | javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'void org.georchestra.security.model.GeorchestraUser.setOAuth2ProviderId(java.lang.String)'
docker-proxy-1                            | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
docker-proxy-1                            | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
docker-proxy-1                            | 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
docker-proxy-1                            | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
docker-proxy-1                            | 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
docker-proxy-1                            | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
docker-proxy-1                            | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
docker-proxy-1                            | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
docker-proxy-1                            | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
docker-proxy-1                            | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
docker-proxy-1                            | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
docker-proxy-1                            | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
docker-proxy-1                            | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
docker-proxy-1                            | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
docker-proxy-1                            | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
docker-proxy-1                            | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
docker-proxy-1                            | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
docker-proxy-1                            | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
docker-proxy-1                            | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
docker-proxy-1                            | 	at java.base/java.lang.Thread.run(Unknown Source)
docker-proxy-1                            | Caused by: 
docker-proxy-1                            | org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'void org.georchestra.security.model.GeorchestraUser.setOAuth2ProviderId(java.lang.String)'
...

**Comment by edevosc2c** [comment] 2023-10-19 06:47
IIRC @tkohr had the same issue?

**Comment by tkohr** [comment] 2023-10-19 07:13
No, I had some issues on master, but finally just due to some old leftovers.

**Comment by jeanpommier** [comment] 2023-10-19 07:48
But this one is about 23.0. Did you check it ?

**Comment by edevosc2c** [comment] 2024-03-21 11:09
Closing as unable to reproduce the issue.

**Closed as not planned** 2024-03-21 11:09 UTC
Labels: bug
