### ISSUE TITLE
[docker] ExtractorApp loading indefinitely

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/docker#5] opened 2017-07-21 08:28 UTC
Everything works well with this docker version of geOrchestra, except extractorapp which loads vainly and indefinitely :

￼Loading...

In logs, one can see :  
```
proxy_1                     | 2017-07-21 08:23:37 statistics [INFO] testadmin|2017/07/21 08:23:37|http://extractorapp:8080/extractorapp/|Project Steering Community|ROLE_MOD_EXTRACTORAPP,ROLE_USER,ROLE_ADMINISTRATOR,ROLE_GN_ADMIN,ROLE_MOD_LDAPADMIN,ROLE_MOD_ANALYTICS
proxy_1                     | 2017-07-21 08:23:37 statistics [INFO] testadmin|2017/07/21 08:23:37|http://extractorapp:8080/extractorapp/resources/lib/externals/ext/resources/css/xtheme-gray.css|Project Steering Community|ROLE_MOD_EXTRACTORAPP,ROLE_USER,ROLE_ADMINISTRATOR,ROLE_GN_ADMIN,ROLE_MOD_LDAPADMIN,ROLE_MOD_ANALYTICS
proxy_1                     | 2017-07-21 08:23:37 statistics [INFO] testadmin|2017/07/21 08:23:37|http://extractorapp:8080/extractorapp/resources/app/css/main.css|Project Steering Community|ROLE_MOD_EXTRACTORAPP,ROLE_USER,ROLE_ADMINISTRATOR,ROLE_GN_ADMIN,ROLE_MOD_LDAPADMIN,ROLE_MOD_ANALYTICS
proxy_1                     | 2017-07-21 08:23:37 statistics [INFO] testadmin|2017/07/21 08:23:37|http://extractorapp:8080/extractorapp/resources/lib/Ext.ux/css/MultiSelect.css|Project Steering Community|ROLE_MOD_EXTRACTORAPP,ROLE_USER,ROLE_ADMINISTRATOR,ROLE_GN_ADMIN,ROLE_MOD_LDAPADMIN,ROLE_MOD_ANALYTICS
proxy_1                     | 2017-07-21 08:23:37 statistics [INFO] testadmin|2017/07/21 08:23:37|http://extractorapp:8080/extractorapp/resources/lib/externals/ext/resources/css/ext-all.css|Project Steering Community|ROLE_MOD_EXTRACTORAPP,ROLE_USER,ROLE_ADMINISTRATOR,ROLE_GN_ADMIN,ROLE_MOD_LDAPADMIN,ROLE_MOD_ANALYTICS
proxy_1                     | 2017-07-21 08:23:37 statistics [INFO] testadmin|2017/07/21 08:23:37|http://extractorapp:8080/extractorapp/resources/app/openlayers_gray_theme/style.css|Project Steering Community|ROLE_MOD_EXTRACTORAPP,ROLE_USER,ROLE_ADMINISTRATOR,ROLE_GN_ADMIN,ROLE_MOD_LDAPADMIN,ROLE_MOD_ANALYTICS
proxy_1                     | 2017-07-21 08:23:37 security [WARN] Error occurred. statuscode: 404, reason: Not Found
proxy_1                     | 2017-07-21 08:23:37 security [WARN] Error occurred. statuscode: 404, reason: Not Found
```
Do you also encounter this problem ?

**Comment by pmauduit** [comment] 2017-07-21 09:19
Which docker composition ? the one from georchestra/georchestra or the one from georchestra/docker ? What about the logs from the extractorapp container ?

**Comment by MaxiReglisse** [comment] 2017-09-01 13:21
i use the docker composition in georchestra/georchestra. you can see the problem on https://georchestra-mshe.univ-fcomte.fr/extractorapp/ using the usual testadmin:testadmin login/password.
but sorry for the log in the extractorapp container, where is it ? what is his name ?

**Comment by MaxiReglisse** [comment] 2017-09-01 13:24
/usr/local/jetty/logs is empty

**Comment by pmauduit** [comment] 2017-09-01 15:39
It seems to be related to a compilation issue ; some JS resources are not found. Do you use the official georchestra images ? if so we probably have a CI / Jenkins issue when autogenerating the docker images.

**Comment by pmauduit** [comment] 2017-09-01 15:41
I can confirm the issue comes from the CI:

```
[INFO] --- exec-maven-plugin:1.1:exec (build-javascript) @ extractorapp ---
[INFO] jsbuild/build.sh: 28: jsbuild/build.sh: /home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/bin/jsbuild: not found
[INFO] creating virtual env and installing jstools...
[INFO] New python executable in /home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/bin/python2
[INFO] Also creating executable in /home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/bin/python
[INFO] Installing setuptools, pip...done.
[INFO] Running virtualenv with interpreter /usr/bin/python2
[INFO] Downloading/unpacking jstools
[INFO]   Running setup.py (path:/tmp/pip-build-3Np4s0/jstools/setup.py) egg_info for package jstools
[INFO] Installing collected packages: jstools
[INFO]   Running setup.py install for jstools
[INFO]     Installing jsbuild script to /home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/bin
[INFO]     Installing jst script to /home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/bin
[INFO]     Installing jsmin script to /home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/bin
[INFO] Successfully installed jstools
[INFO] Cleaning up...
[INFO] done.
[INFO] running jsbuild for main app...
[INFO] Writing to /home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/../src/main/webapp/build/extractorapp.js (579 KB)
[INFO] Traceback (most recent call last):
[INFO]   File "/home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/bin/jsbuild", line 9, in <module>
[INFO]     load_entry_point('JSTools==0.6', 'console_scripts', 'jsbuild')()
[INFO]   File "/home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/build.py", line 96, in build
[INFO]     command()
[INFO]   File "/home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/utils.py", line 31, in caller
[INFO]     return func(args, options, optparser)
[INFO]   File "/home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/build.py", line 87, in default_merge
[INFO]     list_only=options.list_only)
[INFO]   File "/home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/merge.py", line 312, in run
[INFO]     return self.nocat_run(sections, uncompressed, strip_deps, compressor)
[INFO]   File "/home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/merge.py", line 279, in nocat_run
[INFO]     outputfilename, merged = self.do_section(section, cfg)
[INFO]   File "/home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/merge.py", line 198, in do_section
[INFO]     merged = self.merge(cfg)
[INFO]   File "/home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/merge.py", line 156, in merge
[INFO]     files = self.extract_deps(cfg, depmap)
[INFO]   File "/home/jenkins/jobs/georchestra-pipelines/jobs/docker/workspace/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/merge.py", line 142, in extract_deps
[INFO]     raise MissingImport("File from '%s' not found: %s" % (part, fp))
[INFO] jstools.merge.MissingImport: File from 'include' not found: locale/ext-lang-fr.js
[INFO] done.
```

**Comment by pmauduit** [comment] 2017-09-01 15:42
@fvanderbiest file not found: locale/ext-lang-fr.js ? any idea why ?

**Comment by pmauduit** [comment] 2017-09-01 15:52
I got another issue locally, trying to compile extractorapp:

```
extractorapp% mvn generate-sources
[...]
[INFO] Executed tasks
[INFO] 
[INFO] --- exec-maven-plugin:1.1:exec (build-javascript) @ extractorapp ---
[INFO] Traceback (most recent call last):
[INFO]   File "/home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/bin/jsbuild", line 7, in <module>
[INFO]     from jstools.build import build
[INFO]   File "/home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/build.py", line 8, in <module>
[INFO]     from jstools.merge import Merger
[INFO]   File "/home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/merge.py", line 249
[INFO]     print(cat[name], file=catted)
[INFO]                          ^
[INFO] SyntaxError: invalid syntax
[INFO] running jsbuild for main app...
[INFO] Traceback (most recent call last):
[INFO]   File "/home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/bin/jsbuild", line 7, in <module>
[INFO]     from jstools.build import build
[INFO]   File "/home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/build.py", line 8, in <module>
[INFO]     from jstools.merge import Merger
[INFO]   File "/home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/merge.py", line 249
[INFO]     print(cat[name], file=catted)
[INFO]                          ^
[INFO] SyntaxError: invalid syntax
[INFO] done.
[INFO] [NOK] jsbuild failure


```

**Comment by pmauduit** [comment] 2017-09-01 16:03
jstools, which is the tool used for the JS minification has been broken (looking at the error, this is probably due to python2 deprecation, a rapid test using a python3 venv seems to fix the issue). Here is the patch, but I'd like to discuss with my team before considering applying it:

```diff
diff --git a/extractorapp/jsbuild/build.sh b/extractorapp/jsbuild/build.sh
index c1387d4..4157fa8 100755
--- a/extractorapp/jsbuild/build.sh
+++ b/extractorapp/jsbuild/build.sh
@@ -29,7 +29,7 @@ ${mkdir} -p ${releasepath} ${releasepath}/lang
  if  [ ! -d ${venv} ] || [ $? -eq 0 ]; then
      echo "creating virtual env and installing jstools..."
      rm -rf ${venv}
-     virtualenv  --no-site-packages ${venv}
+     virtualenv  --no-site-packages -p python3 ${venv}
      ${venv}/bin/pip install jstools
      echo "done."
  fi;
@@ -60,4 +60,4 @@ ${rm} -rf `find "${releasepath}" -name .svn -type d`
 
 echo "built files and resources placed in src/main/webapp/build"
 
-exit 0
\ No newline at end of file
+exit 0
```

**Comment by fvanderbiest** [comment] 2017-09-03 13:43
> jstools, which is the tool used for the JS minification has been broken

I've been installing it and using it today in a virtualenv with Python 2.7.13 and it still works.
I'd like to better understand what happens here on the build server.

**Comment by fvanderbiest** [comment] 2017-09-03 13:47
> [INFO] jstools.merge.MissingImport: File from 'include' not found: locale/ext-lang-fr.js

The file is in extractorapp/src/main/webapp/lib/externals/ext/src/locale/ext-lang-fr.js and should be picked without errors according to https://github.com/georchestra/georchestra/blob/16.12/extractorapp/jsbuild/main.cfg#L34-L43

**Comment by pmauduit** [comment] 2017-09-04 08:04
On master, without my current patch on my dev environment (not even on the CI server):

```
% mvn clean package
[INFO] ------------------------------------------------------------------------
[INFO] Building Extractorapp Webapp 17.06-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ extractorapp ---
[INFO] Deleting /home/pmauduit/projects/georchestra/georchestra/extractorapp/target
[INFO] Deleting /home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild (includes = [env/**], excludes = [])
[INFO] 
[...]
[INFO] --- exec-maven-plugin:1.1:exec (default) @ extractorapp ---
[INFO] /home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/build.sh: 28: /home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/build.sh: /home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/bin/jsbuild: not found
[INFO] creating virtual env and installing jstools...
[INFO] New python executable in /home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/bin/python2
[INFO] Also creating executable in /home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/bin/python
[INFO] Installing setuptools, pkg_resources, pip, wheel...done.
[INFO] Running virtualenv with interpreter /usr/bin/python2
[INFO] Collecting jstools
[INFO]   Using cached JSTools-1.0-py2-none-any.whl
[INFO] Installing collected packages: jstools
[INFO] Successfully installed jstools-1.0
[INFO] done.
[INFO] running jsbuild for main app...
[INFO] Traceback (most recent call last):
[INFO]   File "/home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/bin/jsbuild", line 7, in <module>
[INFO]     from jstools.build import build
[INFO]   File "/home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/build.py", line 8, in <module>
[INFO]     from jstools.merge import Merger
[INFO]   File "/home/pmauduit/projects/georchestra/georchestra/extractorapp/jsbuild/env/local/lib/python2.7/site-packages/jstools/merge.py", line 249
[INFO]     print(cat[name], file=catted)
[INFO]                          ^
[INFO] SyntaxError: invalid syntax
[INFO] done.
[INFO] [NOK] jsbuild failure
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.056 s
[INFO] Finished at: 2017-09-04T10:03:15+02:00
[INFO] Final Memory: 26M/458M
[INFO] ------------------------------------------------------------------------
```

I cannot understand what you do differently from your side to have it keeping building correctly on your environment.

**Comment by fvanderbiest** [comment] 2017-09-05 08:41
JSTools has switched to python3 with https://github.com/camptocamp/jstools/pull/13 and the package was updated on pypi on 2017-09-01, which explains why we're getting this error now.

The main developer refuses to keep python2 compatibility, so I guess we have no choice here, yep.

**Comment by fvanderbiest** [comment] 2017-09-05 12:00
Should be fixed with the next generation of docker images produced by the CI.

**Closed as completed** 2017-09-05 12:00 UTC
Labels: bug
